config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  default_url_options host: "localhost:3000"
  devise_for :users
  resources :books do
    resources :histories
    resources :comments
    resources :likes
  end
  root to: "books#index"
end

app/models/book.rb
# Book
class Book
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Letsrate
  letsrate_rateable

  attr_accessor :img
  mount_uploader :img, ImgUploader

  field :name, type: String
  field :status, type: String
  field :author, type: String
  field :genre, type: String
  field :img, type: String
  field :description, type: String
  field :likes_count, type: Integer
  field :histories_count, type: Integer

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :histories, dependent: :destroy
  belongs_to :user, class_name: 'User', foreign_key: :user_id



  validates :name, presence: true
  validates :author, presence: true
  validates :genre, presence: true
  validates :description, presence: true
end

app/models/comment.rb
# Comment
class Comment
  include Mongoid::Document
  field :body, type: String
  belongs_to :book
  belongs_to :user
  validates :body, presence: true
end

app/models/history.rb
# History
class History
  include Mongoid::Document
  belongs_to :book, counter_cache: :histories_count
  belongs_to :user
  field :taken_in, type: DateTime
  field :returned_in, type: DateTime
  validates :taken_in, presence: true
end

app/models/like.rb
# Like
class Like
  include Mongoid::Document
  belongs_to :book, counter_cache: :likes_count
  belongs_to :user
  validates :user, uniqueness: { scope: :book }

end

app/models/rate.rb
# Rate
class Rate
  include Mongoid::Document
  include Mongoid::Timestamps
  field :stars, type: Float
  belongs_to :rater, class_name: 'User'
  belongs_to :rateable, polymorphic: true
end

app/models/rating_cache.rb
# Rating
class RatingCache
  include Mongoid::Document
  include Mongoid::Timestamps
  field :avg, type: Float
  field :qty, type: Integer
  belongs_to :cacheable, polymorphic: true
end

app/models/user.rb
# User
class User
  include Mongoid::Document
  include Mongoid::Letsrate

  has_many :books
  has_many :histories
  has_many :likes
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ## Database authenticatable
  field :email,              type: String, default: ''
  field :encrypted_password, type: String, default: ''
  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time
  ## Rememberable
  field :remember_created_at, type: Time
  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable
  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
   #letsrate_rater
end

app/controllers/application_controller.rb
# Application
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :popular, only: :index
  before_action :find_book, only: [:show, :update, :edit, :update, :destroy]
  before_action :update_status, only: :update

  def index
    @books = Book.all.page(params[:page]).per(20)
  end

  def show
    @like = @book.likes.find_by(user_id: current_user.id)
    respond_to do |format|
      format.html
      format.json { render json: @book }
    end
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.create!(book_params)
    redirect_to @book
  end

  def update
    @book.update!(book_params)
    redirect_to book_path(@book.id)
  end

  def destroy
    @book.destroy!
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name, :author, :genre, :status, :img, :description, :user_id)
  end

  def update_status
    if book_params[:status] == 'out'
      History.create(user_id: current_user.id, book_id: @book.id, taken_in: DateTime.now)
    elsif book_params[:status] == 'in'
      @histories = History.where(user_id: current_user.id, returned_in: nil, book_id: @book.id)
      @histories.update(returned_in: DateTime.now) unless @histories.empty?
    end
  end

  def find_book
    @book = Book.find(params[:id])
  end

  def popular
    @popular_books = Book.all.order_by(likes_count: :desc, histories_count: :desc)
  end
end

app/controllers/comments_controller.rb
# Comments
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @book = Book.find(params[:book_id])
    @comment = @book.comments.create!(comment_params)
    respond_to do |format|
      format.html { redirect_to book_path(@book) }
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end
end

app/controllers/histories_controller.rb
# Histories
class HistoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_book, only: [:create, :update]

  def create
    @history = @book.histories.create!(history_params)
    redirect_to book_path(@book.id)
  end

  def update
    @history = History.find(params[:id])
    @history.update(history_params)
    redirect_to book_path(@book.id)
  end

  private

  def history_params
    params.require(:history).permit(:user_id, :book_id, :taken_in, :returned_in)
  end

  def find_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/likes_controller.rb
# Likes
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_book, only: [:create, :destroy]
  def create
    @like = @book.likes.create(like_params)
    respond_to do |format|
      format.html { redirect_to book_path(@book.id) }
      format.js
    end
  end

  def destroy
    @like = @book.likes.find(params[:id])
    @like.delete
    respond_to do |format|
      format.html { redirect_to book_path(@book.id) }
      format.js
    end
  end

  private

  def like_params
    params.require(:like).permit(:book_id, :user_id)
  end

  def find_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/rater_controller.rb
# Rate
class RaterController < ApplicationController
  before_action :authenticate_user!
  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_i, current_user

      render json: true
    else
      render json: false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def json_for(target, options ={})
    options[:scope] ||= self
    options[:url_options] ||= url_options
    target.mongoid_serializer.new(target, options).to_json
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/books/_form.html.haml
%body.body_color
  .back_row
    .row
    .col-lg-2

    .col-lg-8
      .main_head_wrap
        .butts
          = link_to 'Главная', books_path
      %h1.top_h1
      = form_with(model: book, local: true, id: 'form_c') do |form|
        - if book.errors.any?
          #error_explanation
            %h2
              = pluralize(book.errors.count, 'error')
              prohibited this book from being saved:
            %ul
              - book.errors.full_messages.each do |message|
                %li= message
        %br
        .field
          = form.label 'Название'
          = form.text_field :name, id: :book_name
        %br
        .field
          = form.label 'Жанр'
          = form.text_field :genre, id: :book_genre
        %br
        .field
          = form.label 'Автор'
          = form.text_field :author, id: :book_author
        %br
        .field
          = form.label 'Картинка'
          = form.file_field :img, id: :book_img
        %br
        .field
          = form.label 'Описание'
          = form.text_area :description, id: :book_description
          = form.hidden_field :user_id, value: current_user.id
          = form.hidden_field :status, value: 'in'
        %br
        .actions
          = form.submit
    .col-lg-2
      %br

app/views/books/_form_return.html.haml
- @book.histories.each do |h|
  - if h.user.id == current_user.id && h.taken_in != '' && h.returned_in == nil
    = form_for @book, url: @book, method: :put, remote: true, id: 'return' do |book|
      = book.hidden_field :status, value: 'in'
      = book.submit 'Вернуть'
  - elsif h.taken_in != '' && h.returned_in == nil
    %h1 This book was taken by #{h.user.email}

app/views/books/_form_take.html.haml
= form_for @book, url: @book, method: :put, remote: true, id: 'take' do |book|
  = book.hidden_field :status, value: 'out'
  = book.submit 'Взять'

app/views/books/_return.html.haml
= form_for @book, url: @book, method: :put, remote: true, id: 'take' do |book|
  = book.hidden_field :status, value: 'out'
  = book.submit 'Взять'

app/views/books/_take.html.haml
- @book.histories.each do |h|
  - if h.user.id == current_user.id && h.taken_in != '' && h.returned_in == nil
    = form_for @book, url: @book, method: :put, remote: true, id: 'return' do |book|
      = book.hidden_field :status, value: 'in'
      = book.submit 'Вернуть'
  - elsif h.taken_in != '' && h.returned_in == nil
    %h1 This book was taken by #{h.user.email}

app/views/books/edit.html.haml
= render 'form', book: @book

app/views/books/index.html.haml
%body.body_color
  .back_row
    .col-lg-2
    .col-lg-8
      .main_head_wrap
        .butts
          = link_to 'Добавить книгу', new_book_path, method: :get, class: 'newbook'
          = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'exit'
      %h1.top_h1
        Топ 5 книг
      .main_wrap
        .row
          - @popular_books.take(5).each do |b|
            .col-lg-12
              %br
              .book
                %div
                  %img{src: "#{b.img}", class: 'images'}
                .desc
                  .desc_name
                    = link_to b.name, book_path(b)
                  %table.tabs
                    %tr
                      %td
                        |
                        = b.genre
                        |
                        %img{src: b.status == 'in' ? "/green2.png" : "/red.png", class: 'status'}
                    %tr
                      %td
                        = b.description
                        %br
                        %br
                        .author
                          = b.author
      %h1.top_h1
        Все книги
      .main_wrap
        .row
          - @books.order(created_at: 'desc').each do |b|
            .col-lg-12
              %br
              .book
                %div
                  %img{src: "#{b.img}", class: 'images'}
                .desc
                  .desc_name
                    = link_to b.name, book_path(b)
                  %table.tabs
                    %tr
                      %td
                        |
                        = b.genre
                        |
                        - if b.status == 'in'
                          Статус
                          %img{src: "/green2.png", class: 'status'}
                        - else
                          Статус
                          %img{src: "/red.png", class: 'status'}
                    %tr
                      %td
                        = b.description
                        %br
                        %br
                        .author
                          = b.author
        = paginate @books
      .main_foot_wrap
    .col-lg-2
  %br

app/views/books/new.html.haml
= render 'form', book: @book

app/views/books/show.html.haml
%require_tree
-#%div.header
-#  %div
-#    %img{src: '/uploads/book.png', class: 'logo'}
-#  %div
-#    %p
-#      Search
-#      %input{type: 'search', class: 'search'}
.main
  %br
  %br
  .home
    = button_to 'Главная', books_path, method: 'get'
    - if @book.user_id == current_user.id
      .dropdown
        %input.btn.btn-primary.dropdown-toggle{'data-toggle' => 'dropdown',:value => '' ,readonly: 'true', id: 'drop'}
        %ul.dropdown-menu
          %li
            - if @book.status == 'in'
              = button_to 'Изменить', edit_book_path(@book),  method: :get
          %li
            = button_to 'Удалить', [@book],  method: :delete
          %li

  %br
  %br
  %br


  .row
    .col-md-4
      %img{src: "#{@book.img}", class: 'image_show'}
      .take_like
        .row
          .col-md-6
            - if @book.status == 'in'
              #take
                = render 'books/form_take'
            - elsif @book.status == 'out'
              #return
                = render 'books/form_return'
          .col-md-6
            - if @like != nil && @like.user_id == current_user.id && @like.book_id == @book.id
              #dislike
                = render 'likes/form_dislike'
            - elsif @like.nil? || @like.user_id != current_user.id && @like.book_id != @book.id
              #like
                = render 'likes/form_like'
    .col-md-8
      .info
        %p
          Название:
          %strong= @book.name
        %p
          Статус:
          %img{src: @book.status == 'in' ? "/green2.png" : "/red.png", class: 'status'}
        %p
          Автор:
          %strong= @book.author
        %p
          Жанр:
          %strong= @book.genre
        %p
          %strong Описание:
          %br
          %br
          = @book.description
        %p
          /Рейтинг:
          /%strong= rating_for @book
        %br
  %br
  .footer
    .row
      .col-lg-6
        %h2 Комментарии:
        #com
          = render @book.comments.order_by(created_at: 'desc')
        = render 'comments/form'
      .col-lg-6
        .histories
          %h2 История:
          %table
            %thead
              %tr
                %th Пользователь
                %th Когда взял
                %th Когда вернул
            %tbody
              - @book.histories.order_by(taken_in: 'desc').each do |history|
                %tr
                  %td= history.user.email
                  %td= history.taken_in
                  %td= history.returned_in
          %br

app/views/books/update_status_in.js.haml
:plain
  $("#take").html("#{ j( render 'take') }");

app/views/books/update_status_out.js.haml
:plain
  $("#return").html("#{ j( render 'return') }");

app/views/comments/_comment.html.haml
.comment
  %br
  %br
  %table.comment_tr
    %tr
      %th
        %strong= comment.user.email
      %th.com_body
        = comment.body
  %br
  %br
%hr

app/views/comments/_form.html.haml
= form_with(model: [ @book, @book.comments.build ], remote: true) do |form|
  = form.text_area :body, id: "comm"
  = form.hidden_field :user_id, value: current_user.id
  = form.hidden_field :book_id, value: @book.id
  = form.submit "Написать", id: "but_comm"

app/views/comments/create.js.haml
:plain
  $('#com').html("#{ j( render @book.comments ) }");

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Library
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/likes/_dislike.html.haml
= link_to("<span class=\"glyphicon glyphicon-heart\" style=\"color:red\"></span>".html_safe+" #{@book.likes.count}",book_likes_path(@book.id, like: {user_id: current_user.id, book_id: @book.id}),method: :post, remote: true, id: "like" )

app/views/likes/_form_dislike.html.haml
= link_to("<span class=\"glyphicon glyphicon-heart-empty\" style=\"color:red\"></span>".html_safe+" #{@book.likes.count}",[ @like.book, @like ],  method: :delete, remote: true, id: "dislike")

app/views/likes/_form_like.html.haml
= link_to("<span class=\"glyphicon glyphicon-heart\" style=\"color:red\"></span>".html_safe+" #{@book.likes.count}",book_likes_path(@book.id, like: {user_id: current_user.id, book_id: @book.id}),method: :post, remote: true, id: "like" )

app/views/likes/_like.html.haml
= link_to "<span class=\"glyphicon glyphicon-heart-empty\" style=\"color:red\"></span>".html_safe+" #{@book.likes.count}", [ @like.book, @like], remote: true,  method: :delete, id: "dislike"

app/views/likes/create.js.haml
:plain
  $('#like').html("#{ j( render 'like') }");

app/views/likes/destroy.js.haml
:plain
  $('#dislike').html("#{ j(render 'dislike') }");